#include <search.h>
#include <stdio.h>

#define MAX_RULES 188

typedef struct
{
    char *non_terminal;
    char *terminal;
    char *production;
} ParsingRule;
ParsingRule parsing_table[MAX_RULES] = {
    {"program", "f", "fdecls decs st_seq ."},
    {"fdecls", "f", "fdec fdecls_"},
    {"fdecls_", "int", "ε"},
    {"fdecls_", ";", "; fdec fdecls_"},
    {"fdecls_", "double", "ε"},
    {"fdec", "d", "def type fname ( params ) decs st_seq fed"},
    {"params", "t", "type var params_"},
    {"params_", ")", "ε"},
    {"params_", ",", ", type var params_"},
    {"fname", "i", "id"},
    {"decs", "d", "decl decs_"},
    {"decs_", "if", "ε"},
    {"decs_", ".", "ε"},
    {"decs_", "print", "ε"},
    {"decs_", "return", "ε"},
    {"decs_", "char", "ε"},
    {"decs_", "fed", "ε"},
    {"decs_", "while", "ε"},
    {"decs_", ";", "ε"},
    {"decl", "t", "type varlist"},
    {"type", "i", "int"},
    {"type", "d", "double"},
    {"varlist", "v", "var , varlist_"},
    {"varlist_", "if", "ε"},
    {"varlist_", ".", "ε"},
    {"varlist_", "print", "ε"},
    {"varlist_", "return", "ε"},
    {"varlist_", "char", "ε"},
    {"varlist_", "fed", "ε"},
    {"varlist_", "while", "ε"},
    {"varlist_", ",", ", var varlist_"},
    {"varlist_", ";", "ε"},
    {"st_seq", "s", "statement ; st_seq"},
    {"statement", ".", "ε"},
    {"statement", "else", "ε"},
    {"statement", "fed", "ε"},
    {"statement", "od", "ε"},
    {"statement", ";", "ε"},
    {"statement", "fi", "ε"},
    {"statement", "v", "var = expr"},
    {"statement", "i", "if bexpr then st_seq st_seq_ fi"},
    {"statement", "w", "while bexpr do st_seq od"},
    {"statement", "p", "print expr"},
    {"statement", "r", "return expr"},
    {"st_seq_", "e", "else st_seq"},
    {"st_seq_", "fi", "ε"},
    {"expr", "t", "term expr_"},
    {"expr_", "+", "+ term expr_"},
    {"expr_", "and", "ε"},
    {"expr_", ">", "ε"},
    {"expr_", "-", "- term expr_"},
    {"expr_", "<>", "ε"},
    {"expr_", "]", "ε"},
    {"expr_", "then", "ε"},
    {"expr_", ".", "ε"},
    {"expr_", "else", "ε"},
    {"expr_", "do", "ε"},
    {"expr_", "<", "ε"},
    {"expr_", "fed", "ε"},
    {"expr_", "od", "ε"},
    {"expr_", ">=", "ε"},
    {"expr_", ")", "ε"},
    {"expr_", "or", "ε"},
    {"expr_", ",", "ε"},
    {"expr_", ";", "ε"},
    {"expr_", "fi", "ε"},
    {"expr_", "==", "ε"},
    {"expr_", "<=", "ε"},
    {"term", "f", "factor term_"},
    {"term_", "*", "* factor term_"},
    {"term_", "+", "ε"},
    {"term_", '%', "% factor term_"},
    {"term_", "and", "ε"},
    {"term_", ">", "ε"},
    {"term_", "-", "ε"},
    {"term_", "<>", "ε"},
    {"term_", "]", "ε"},
    {"term_", "then", "ε"},
    {"term_", "/", "/ factor term_"},
    {"term_", ".", "ε"},
    {"term_", "else", "ε"},
    {"term_", "do", "ε"},
    {"term_", "<", "ε"},
    {"term_", "fed", "ε"},
    {"term_", "od", "ε"},
    {"term_", ">=", "ε"},
    {"term_", ")", "ε"},
    {"term_", "or", "ε"},
    {"term_", ",", "ε"},
    {"term_", ";", "ε"},
    {"term_", "fi", "ε"},
    {"term_", "==", "ε"},
    {"term_", "<=", "ε"},
    {"exprseq", "e", "expr , exprseq_"},
    {"exprseq_", ")", "ε"},
    {"exprseq_", ",", ", expr exprseq_"},
    {"bexpr", "b", "bterm bexpr_"},
    {"bexpr_", "then", "ε"},
    {"bexpr_", "do", "ε"},
    {"bexpr_", ")", "ε"},
    {"bexpr_", "o", "or bfactor bterm_"},
    {"bterm", "b", "bfactor bterm_"},
    {"bterm_", "then", "ε"},
    {"bterm_", "do", "ε"},
    {"bterm_", ")", "ε"},
    {"bterm_", "or", "ε"},
    {"bterm_", "a", "and bfactor bterm_"},
    {"bfactor", "e", "expr comp expr"},
    {"bfactor", "(", "( bexpr )"},
    {"bfactor", "n", "not bfactor"},
    {"comp", ">", ">="},
    {"comp", "=", "=="},
    {"comp", "<", "<>"},
    {"var", "i", "id [ expr ]"},
    {"id", "l", "letter id_"},
    {"id_", "*", "ε"},
    {"id_", "if", "ε"},
    {"id_", "+", "ε"},
    {"id_", '%', "ε"},
    {"id_", "and", "ε"},
    {"id_", ">", "ε"},
    {"id_", "=", "ε"},
    {"id_", "-", "ε"},
    {"id_", "<>", "ε"},
    {"id_", "]", "ε"},
    {"id_", "then", "ε"},
    {"id_", "/", "ε"},
    {"id_", ".", "ε"},
    {"id_", "print", "ε"},
    {"id_", "else", "ε"},
    {"id_", "return", "ε"},
    {"id_", "[", "ε"},
    {"id_", "(", "ε"},
    {"id_", "do", "ε"},
    {"id_", "<", "ε"},
    {"id_", "int", "ε"},
    {"id_", "char", "ε"},
    {"id_", "fed", "ε"},
    {"id_", "od", "ε"},
    {"id_", ">=", "ε"},
    {"id_", ")", "ε"},
    {"id_", "or", "ε"},
    {"id_", "while", "ε"},
    {"id_", ",", "ε"},
    {"id_", ";", "ε"},
    {"id_", "fi", "ε"},
    {"id_", "<=", "ε"},
    {"id_", "double", "ε"},
    {"id_", "l", "letter id_"},
    {"id_", "d", "digit id_"},
    {"number", "i", "integer"},
    {"number", "d", "Double"},
    {"Double", "i", "integer . integer"},
    {"integer", "d", "digit integer_"},
    {"integer_", "*", "ε"},
    {"integer_", "+", "ε"},
    {"integer_", '%', "ε"},
    {"integer_", "and", "ε"},
    {"integer_", ">", "ε"},
    {"integer_", "-", "ε"},
    {"integer_", "<>", "ε"},
    {"integer_", "]", "ε"},
    {"integer_", "then", "ε"},
    {"integer_", "/", "ε"},
    {"integer_", ".", "ε"},
    {"integer_", "do", "ε"},
    {"integer_", "<", "ε"},
    {"integer_", "fed", "ε"},
    {"integer_", "od", "ε"},
    {"integer_", ">=", "ε"},
    {"integer_", ")", "ε"},
    {"integer_", "or", "ε"},
    {"integer_", ",", "ε"},
    {"integer_", ";", "ε"},
    {"integer_", "fi", "ε"},
    {"integer_", "<=", "ε"},
    {"integer_", "d", "digit integer_"},
    {"factor", "(", "( expr )"},
    {"factor", "v", "var"},
    {"factor", "n", "number"},
    {"factor", "f", "fname ( exprseq )"},
    {"letter", "char", "ε"},
    {"digit", "num", "ε"},
    {"digits_", "d", "digits_"},
    {"exponent", "e", "E sign digit digits_"},
    {"sign", "+", "+"},
    {"sign", "-", "-"},
    {"sign", "num", "ε"},
};

int main()
{
    printf("LL(1) Parsing Table Loaded. Use hash map lookup to access rules.\n");
    return 0;
}
