#include <search.h>
#include <stdio.h>

#define MAX_RULES 287

typedef struct {
    char *non_terminal;
    char *terminal;
    char *production;
} ParsingRule;

ParsingRule parsing_table[MAX_RULES] = {
    {"program", "f", "fdecls decs st_seq ."},
    {"fdecls", "f", "fdec fdecls_"},
    {"fdecls_", ";", "; fdec fdecls_"},
    {"fdecls_", "int", "ε"},
    {"fdecls_", "double", "ε"},
    {"fdec", "d", "def type fname ( params ) decs st_seq fed"},
    {"params", "t", "type var params_"},
    {"params_", ",", ", type var params_"},
    {"params_", ")", "ε"},
    {"fname", "i", "id"},
    {"decs", "d", "decl decs_"},
    {"decs_", "m", "ε"},
    {"decs_", "r", "ε"},
    {"decs_", "j", "ε"},
    {"decs_", "z", "ε"},
    {"decs_", "n", "ε"},
    {"decs_", "e", "ε"},
    {"decs_", "fed", "ε"},
    {"decs_", "print", "ε"},
    {"decs_", "y", "ε"},
    {"decs_", "g", "ε"},
    {"decs_", ";", "ε"},
    {"decs_", "d", "ε"},
    {"decs_", "k", "ε"},
    {"decs_", "l", "ε"},
    {"decs_", "return", "ε"},
    {"decs_", "h", "ε"},
    {"decs_", "w", "ε"},
    {"decs_", "while", "ε"},
    {"decs_", "if", "ε"},
    {"decs_", "i", "ε"},
    {"decs_", "o", "ε"},
    {"decs_", "s", "ε"},
    {"decs_", "a", "ε"},
    {"decs_", "u", "ε"},
    {"decs_", "q", "ε"},
    {"decs_", ".", "ε"},
    {"decs_", "x", "ε"},
    {"decs_", "c", "ε"},
    {"decs_", "f", "ε"},
    {"decs_", "p", "ε"},
    {"decs_", "v", "ε"},
    {"decs_", "b", "ε"},
    {"decs_", "t", "ε"},
    {"decl", "t", "type varlist"},
    {"type", "d", "double"},
    {"type", "i", "int"},
    {"varlist", "v", "var , varlist_"},
    {"varlist_", "m", "ε"},
    {"varlist_", "r", "ε"},
    {"varlist_", "j", "ε"},
    {"varlist_", "z", "ε"},
    {"varlist_", "n", "ε"},
    {"varlist_", "e", "ε"},
    {"varlist_", "fed", "ε"},
    {"varlist_", "print", "ε"},
    {"varlist_", "y", "ε"},
    {"varlist_", "g", "ε"},
    {"varlist_", ";", "ε"},
    {"varlist_", "d", "ε"},
    {"varlist_", ",", ", var varlist_"},
    {"varlist_", "k", "ε"},
    {"varlist_", "l", "ε"},
    {"varlist_", "return", "ε"},
    {"varlist_", "h", "ε"},
    {"varlist_", "w", "ε"},
    {"varlist_", "while", "ε"},
    {"varlist_", "if", "ε"},
    {"varlist_", "i", "ε"},
    {"varlist_", "o", "ε"},
    {"varlist_", "s", "ε"},
    {"varlist_", "a", "ε"},
    {"varlist_", "u", "ε"},
    {"varlist_", "q", "ε"},
    {"varlist_", ".", "ε"},
    {"varlist_", "x", "ε"},
    {"varlist_", "c", "ε"},
    {"varlist_", "f", "ε"},
    {"varlist_", "p", "ε"},
    {"varlist_", "v", "ε"},
    {"varlist_", "b", "ε"},
    {"varlist_", "t", "ε"},
    {"st_seq", "s", "statement ; st_seq"},
    {"statement", "r", "return expr"},
    {"statement", "fed", "ε"},
    {"statement", ";", "ε"},
    {"statement", "od", "ε"},
    {"statement", "fi", "ε"},
    {"statement", "w", "while bexpr do st_seq od"},
    {"statement", "i", "if bexpr then st_seq st_seq_ fi"},
    {"statement", ".", "ε"},
    {"statement", "else", "ε"},
    {"statement", "p", "print expr"},
    {"statement", "v", "var = expr"},
    {"st_seq_", "e", "else st_seq"},
    {"st_seq_", "fi", "ε"},
    {"expr", "t", "term expr_"},
    {"expr_", "then", "ε"},
    {"expr_", "-", "- term expr_"},
    {"expr_", "fed", "ε"},
    {"expr_", "==", "ε"},
    {"expr_", ">=", "ε"},
    {"expr_", "<=", "ε"},
    {"expr_", ";", "ε"},
    {"expr_", "<>", "ε"},
    {"expr_", "od", "ε"},
    {"expr_", ",", "ε"},
    {"expr_", "or", "ε"},
    {"expr_", ")", "ε"},
    {"expr_", ">", "ε"},
    {"expr_", "fi", "ε"},
    {"expr_", "+", "+ term expr_"},
    {"expr_", "<", "ε"},
    {"expr_", "do", "ε"},
    {"expr_", ".", "ε"},
    {"expr_", "else", "ε"},
    {"expr_", "and", "ε"},
    {"expr_", "]", "ε"},
    {"term", "f", "factor term_"},
    {"term_", "then", "ε"},
    {"term_", "-", "ε"},
    {"term_", "fed", "ε"},
    {"term_", "==", "ε"},
    {"term_", ">=", "ε"},
    {"term_", "<=", "ε"},
    {"term_", ";", "ε"},
    {"term_", "<>", "ε"},
    {"term_", "od", "ε"},
    {"term_", ",", "ε"},
    {"term_", "or", "ε"},
    {"term_", ")", "ε"},
    {"term_", ">", "ε"},
    {"term_", "fi", "ε"},
    {"term_", "+", "ε"},
    {"term_", "<", "ε"},
    {"term_", "*", "* factor term_"},
    {"term_", "do", "ε"},
    {"term_", ".", "ε"},
    {"term_", "/", "/ factor term_"},
    {"term_", "else", "ε"},
    {"term_", "%", "% factor term_"},
    {"term_", "and", "ε"},
    {"term_", "]", "ε"},
    {"exprseq", "e", "expr , exprseq_"},
    {"exprseq_", ",", ", expr exprseq_"},
    {"exprseq_", ")", "ε"},
    {"bexpr", "b", "bterm bexpr_"},
    {"bexpr_", "then", "ε"},
    {"bexpr_", ")", "ε"},
    {"bexpr_", "o", "or bfactor bterm_"},
    {"bexpr_", "do", "ε"},
    {"bterm", "b", "bfactor bterm_"},
    {"bterm_", "then", "ε"},
    {"bterm_", "or", "ε"},
    {"bterm_", ")", "ε"},
    {"bterm_", "a", "and bfactor bterm_"},
    {"bterm_", "do", "ε"},
    {"bfactor", "n", "not bfactor"},
    {"bfactor", "(", "( bexpr )"},
    {"bfactor", "e", "expr comp expr"},
    {"comp", "=", "=="},
    {"comp", ">", ">="},
    {"comp", "<", "<>"},
    {"var", "i", "id [ expr ]"},
    {"id", "l", "letter id_"},
    {"id_", "m", "ε"},
    {"id_", "then", "ε"},
    {"id_", "r", "ε"},
    {"id_", "j", "ε"},
    {"id_", "z", "ε"},
    {"id_", "n", "ε"},
    {"id_", "(", "ε"},
    {"id_", "-", "ε"},
    {"id_", "e", "ε"},
    {"id_", "fed", "ε"},
    {"id_", ">=", "ε"},
    {"id_", "<=", "ε"},
    {"id_", "print", "ε"},
    {"id_", "y", "ε"},
    {"id_", "[", "ε"},
    {"id_", "g", "ε"},
    {"id_", ";", "ε"},
    {"id_", "d", "ε"},
    {"id_", "<>", "ε"},
    {"id_", "=", "ε"},
    {"id_", "od", "ε"},
    {"id_", ",", "ε"},
    {"id_", "k", "ε"},
    {"id_", "l", "ε"},
    {"id_", "or", "ε"},
    {"id_", "return", "ε"},
    {"id_", ")", "ε"},
    {"id_", ">", "ε"},
    {"id_", "fi", "ε"},
    {"id_", "h", "ε"},
    {"id_", "int", "ε"},
    {"id_", "w", "ε"},
    {"id_", "+", "ε"},
    {"id_", "while", "ε"},
    {"id_", "if", "ε"},
    {"id_", "<", "ε"},
    {"id_", "i", "ε"},
    {"id_", "o", "ε"},
    {"id_", "s", "ε"},
    {"id_", "a", "ε"},
    {"id_", "*", "ε"},
    {"id_", "double", "ε"},
    {"id_", "u", "ε"},
    {"id_", "do", "ε"},
    {"id_", "q", "ε"},
    {"id_", ".", "ε"},
    {"id_", "/", "ε"},
    {"id_", "x", "ε"},
    {"id_", "c", "ε"},
    {"id_", "f", "ε"},
    {"id_", "else", "ε"},
    {"id_", "p", "ε"},
    {"id_", "%", "ε"},
    {"id_", "and", "ε"},
    {"id_", "]", "ε"},
    {"id_", "v", "ε"},
    {"id_", "b", "ε"},
    {"id_", "t", "ε"},
    {"number", "i", "integer"},
    {"number", "D", "Double"},
    {"Double", "i", "integer . integer"},
    {"integer", "d", "digit integer_"},
    {"integer_", "then", "ε"},
    {"integer_", "-", "ε"},
    {"integer_", "fed", "ε"},
    {"integer_", ">=", "ε"},
    {"integer_", "<=", "ε"},
    {"integer_", ";", "ε"},
    {"integer_", "d", "digit integer_"},
    {"integer_", "<>", "ε"},
    {"integer_", "od", "ε"},
    {"integer_", ",", "ε"},
    {"integer_", "or", "ε"},
    {"integer_", ")", "ε"},
    {"integer_", ">", "ε"},
    {"integer_", "fi", "ε"},
    {"integer_", "+", "ε"},
    {"integer_", "<", "ε"},
    {"integer_", "*", "ε"},
    {"integer_", "do", "ε"},
    {"integer_", ".", "ε"},
    {"integer_", "/", "ε"},
    {"integer_", "%", "ε"},
    {"integer_", "and", "ε"},
    {"integer_", "]", "ε"},
    {"factor", "n", "number"},
    {"factor", "(", "( expr )"},
    {"factor", "f", "fname ( exprseq )"},
    {"factor", "v", "var"},
    {"letter", "m", "m"},
    {"letter", "r", "r"},
    {"letter", "j", "j"},
    {"letter", "z", "z"},
    {"letter", "n", "n"},
    {"letter", "e", "e"},
    {"letter", "y", "y"},
    {"letter", "g", "g"},
    {"letter", "d", "d"},
    {"letter", "k", "k"},
    {"letter", "l", "l"},
    {"letter", "h", "h"},
    {"letter", "w", "w"},
    {"letter", "i", "i"},
    {"letter", "o", "o"},
    {"letter", "s", "s"},
    {"letter", "a", "a"},
    {"letter", "u", "u"},
    {"letter", "q", "q"},
    {"letter", "x", "x"},
    {"letter", "c", "c"},
    {"letter", "f", "f"},
    {"letter", "p", "p"},
    {"letter", "v", "v"},
    {"letter", "b", "b"},
    {"letter", "t", "t"},
    {"digit", "n", "num"},
    {"digits_", "d", "digits_"},
    {"exponent", "e", "e sign digit digits_"},
    {"exponent", "E", "E sign digit digits_"},
    {"sign", "-", "-"},
    {"sign", "+", "+"},
    {"sign", "num", "ε"},
};

int main() {
    printf("LL(1) Parsing Table Loaded. Use hash map lookup to access rules.\n");
    return 0;
}
